{
 "title": "MyDashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "2s",
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time()-process_start_time_seconds{instance=\"ehr-server-dev.cpptl.co:80\",job=\"monitoring\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nodejs_heap_space_size_used_bytes)/1024/1024"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"monitoring\"}/1024/1024",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"monitoring\"}/1024/1024",
     "legendFormat": "Virtual  Memory"
    },
    {
     "expr": "sum(nodejs_gc_reclaimed_bytes_total{gctype=\"MarkSweepCompact\"})/1024/1024",
     "legendFormat": "GC Reclaimed Memory"
    },
    { "expr": "process_heap_bytes/1024/1024", "legendFormat": "Process Heap " },
    {
     "expr": "count(nodejs_heap_space_size_used_bytes)",
     "legendFormat": "Processes"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count) by (code)"
    }
   ]
  },
  {
   "title": "HTTP Request Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_sum) / sum(http_request_duration_seconds_count)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(process_cpu_user_seconds_total[1m]) * 100  / scalar(count(process_cpu_seconds_total)))"
    }
   ]
  },
  {
   "title": "CPU  Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_user_seconds_total[1m])) / count(process_cpu_seconds_total) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"monitoring\"})-sum(nodejs_heap_space_size_used_bytes)"
    }
   ]
  },
  {
   "title": "Memory Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(nodejs_heap_space_size_total_bytes) - sum(nodejs_heap_space_size_used_bytes) ) / sum(nodejs_heap_space_size_total_bytes) * 100"
    }
   ]
  },
  {
   "title": "GC Allocations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(nodejs_gc_reclaimed_bytes_total[4h])"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{job=\"monitoring\"}/1024",
     "legendFormat": "Max"
    },
    {
     "expr": "process_open_fds{job=\"monitoring\"}/1024",
     "legendFormat": "Open"
    }
   ]
  }
 ]
}